---
- import_tasks: directories.yml
  tags: app-install-directories

- name: Create .env file
  template:
    src: "env.j2"
    dest: "/tmp/{{ item.key }}.env"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
  with_dict: "{{ sites }}"

- name: Copy .env file into web root
  command: rsync -ac --info=NAME /tmp/{{ item.key }}.env {{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/.env
  with_dict: "{{ sites }}"
  register: env_file
  changed_when: env_file.stdout == item.key + '.env'

- name: Add known_hosts
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.key | default(omit) }}"
    path: "{{ item.path | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  become: no
  with_items: "{{ known_hosts | default([]) }}"

- include_tasks: tasks/composer-authentications.yml
  vars:
    site: "{{ item.key }}"
    working_dir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/"
  no_log: true
  with_dict: "{{ sites }}"

- name: Install Dependencies with Composer
  composer:
    no_dev: no
    optimize_autoloader: no
    working_dir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/"
  become: no
  with_dict: "{{ sites }}"

- name: Run the migrations
  command: "/usr/bin/php artisan migrate --force chdir={{ www_root }}/{{ item.key }}/current"
  with_dict: "{{ sites }}"

- name: Generate app key
  command: "/usr/bin/php artisan key:generate chdir={{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}"
  with_dict: "{{ sites }}"
